# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accendo', '0005_auto_20160719_1955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nfcuser',
            old_name='added_date',
            new_name='date_added',
        ),
    ]
