# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=20)),
                ('card_id', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=20)),
                ('role', models.CharField(max_length=20)),
                ('added_date', models.DateTimeField(verbose_name='date added')),
            ],
        ),
    ]
