# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accendo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='another_id',
            field=models.CharField(default='larry', max_length=20),
            preserve_default=False,
        ),
    ]
