# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 19:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accendo', '0004_auto_20160719_1952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccendoUser',
            new_name='NFCUser',
        ),
    ]
