# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accendo', '0008_auto_20160720_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmisevent',
            name='active_dates',
        ),
        migrations.RemoveField(
            model_name='cmisevent',
            name='course',
        ),
        migrations.RemoveField(
            model_name='cmisevent',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='cmisevent',
            name='date_to',
        ),
        migrations.RemoveField(
            model_name='cmisevent',
            name='day',
        ),
        migrations.RemoveField(
            model_name='cmisevent',
            name='department',
        ),
        migrations.RemoveField(
            model_name='cmisevent',
            name='finish_time',
        ),
        migrations.RemoveField(
            model_name='cmisevent',
            name='room',
        ),
        migrations.RemoveField(
            model_name='cmisevent',
            name='site',
        ),
        migrations.RemoveField(
            model_name='cmisevent',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='cmisevent',
            name='subject',
        ),
        migrations.AddField(
            model_name='cmisevent',
            name='ActivityType',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='cmisevent',
            name='Dates',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='cmisevent',
            name='Day',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='cmisevent',
            name='Event',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='cmisevent',
            name='EventType',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='cmisevent',
            name='Finish',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='cmisevent',
            name='Id',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='cmisevent',
            name='Instance',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='cmisevent',
            name='Room',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='cmisevent',
            name='Source',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='cmisevent',
            name='Start',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='cmisevent',
            name='SubjectCode',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='cmisevent',
            name='SubjectName',
            field=models.CharField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='cmisevent',
            name='SubjectSubGroup',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
