# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accendo', '0010_auto_20160722_1838'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CMISEvent',
        ),
    ]
