# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accendo', '0011_delete_cmisevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMISEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_id', models.CharField(max_length=20)),
                ('event_id', models.CharField(max_length=20)),
                ('teacher_id', models.CharField(max_length=20)),
                ('Instance', models.CharField(default='NULL', max_length=50)),
                ('Event', models.CharField(default='NULL', max_length=50)),
                ('CMISId', models.CharField(default='NULL', max_length=50)),
                ('Day', models.CharField(default='NULL', max_length=50)),
                ('Start', models.CharField(default='NULL', max_length=50)),
                ('Finish', models.CharField(default='NULL', max_length=50)),
                ('Room', models.CharField(default='NULL', max_length=50)),
                ('Dates', models.CharField(default='NULL', max_length=50)),
                ('SubjectCode', models.CharField(default='NULL', max_length=50)),
                ('SubjectName', models.CharField(default='NULL', max_length=50)),
                ('ActivityType', models.CharField(default='NULL', max_length=50)),
                ('SubjectSubGroup', models.CharField(default='NULL', max_length=50)),
                ('Source', models.CharField(default='NULL', max_length=50)),
                ('EventType', models.CharField(default='NULL', max_length=50)),
            ],
        ),
    ]
