# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-22 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accendo', '0015_auto_20160722_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmisevent',
            name='Room',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='cmisevent',
            name='SubjectCode',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AlterField(
            model_name='cmisevent',
            name='SubjectName',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
