# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accendo', '0017_auto_20160724_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfcuser',
            name='pin',
            field=models.CharField(default='0000', max_length=200),
        ),
    ]
