# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accendo', '0019_nfcuser_wrong_pin_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfcuser',
            name='status',
            field=models.CharField(default='OK', max_length=200),
        ),
    ]
