# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accendo', '0020_nfcuser_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmisevent',
            name='event_id',
        ),
    ]
