# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accendo', '0023_auto_20160804_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendevent',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='attendevent',
            name='tid',
        ),
        migrations.DeleteModel(
            name='AttendEvent',
        ),
    ]
