# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accendo', '0024_auto_20160804_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20)),
                ('card_id', models.CharField(default='NULL', max_length=20)),
                ('EventID', models.CharField(default='NULL', max_length=50)),
            ],
        ),
    ]
